name: Continuous Integration

on: [push]

jobs:
  test-xcode:
    name: Run tests using Xcode
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: [
          "platform=macOS",
          "platform=iOS Simulator,name=iPhone Xs", 
          "platform=tvOS Simulator,name=Apple TV",
          "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: xcrun xcodebuild test
      run: |
        xcrun xcodebuild test -destination "${{ matrix.destination }}" -project "Differ.xcodeproj" -scheme "Differ"
        bash <(curl -s https://codecov.io/bash)

  test-swift-package-manager:
    name: Run tests using Swift Package Manager
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: swift test
      run: swift test
